steps:
  - name: gcr.io/cloud-builders/git
    args: ['fetch', '--unshallow']
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['run', 'generate']
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-d", "dist", "gs://www.apigear.io"]

