body:
  title: Workflow for software projects
  text: >
    ApiGear provides a digital workflow for API driven software creation.
    Customers design their software interfaces collaborative online in a team,
    view the document in the developer portal and download their SDKs for integration in their favourite programming language.
